// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package uart_ctrl_pkg;

    localparam UART_CTRL_DATA_WIDTH = 32;
    localparam UART_CTRL_MIN_ADDR_WIDTH = 6;
    localparam UART_CTRL_SIZE = 'h28;

    typedef struct {
        logic [7:0] next;
    } uart_ctrl__RBR_THR__DATA__in_t;

    typedef struct {
        uart_ctrl__RBR_THR__DATA__in_t DATA;
    } uart_ctrl__RBR_THR__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__IIR__TYPE__in_t;

    typedef struct {
        logic [2:0] next;
    } uart_ctrl__IIR__ID__in_t;

    typedef struct {
        uart_ctrl__IIR__TYPE__in_t TYPE;
        uart_ctrl__IIR__ID__in_t ID;
    } uart_ctrl__IIR__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__DR__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__OE__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__PE__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__FE__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__BI__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__THRE__in_t;

    typedef struct {
        logic next;
    } uart_ctrl__LSR__TEMT__in_t;

    typedef struct {
        uart_ctrl__LSR__DR__in_t DR;
        uart_ctrl__LSR__OE__in_t OE;
        uart_ctrl__LSR__PE__in_t PE;
        uart_ctrl__LSR__FE__in_t FE;
        uart_ctrl__LSR__BI__in_t BI;
        uart_ctrl__LSR__THRE__in_t THRE;
        uart_ctrl__LSR__TEMT__in_t TEMT;
    } uart_ctrl__LSR__in_t;

    typedef struct {
        logic [7:0] next;
    } uart_ctrl__MSR__DATA__in_t;

    typedef struct {
        uart_ctrl__MSR__DATA__in_t DATA;
    } uart_ctrl__MSR__in_t;

    typedef struct {
        uart_ctrl__RBR_THR__in_t RBR_THR;
        uart_ctrl__IIR__in_t IIR;
        uart_ctrl__LSR__in_t LSR;
        uart_ctrl__MSR__in_t MSR;
    } uart_ctrl__in_t;

    typedef struct {
        logic [7:0] value;
    } uart_ctrl__RBR_THR__DATA__out_t;

    typedef struct {
        logic [23:0] value;
    } uart_ctrl__RBR_THR__RSVD__out_t;

    typedef struct {
        uart_ctrl__RBR_THR__DATA__out_t DATA;
        uart_ctrl__RBR_THR__RSVD__out_t RSVD;
    } uart_ctrl__RBR_THR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_ctrl__DLL__DATA__out_t;

    typedef struct {
        uart_ctrl__DLL__DATA__out_t DATA;
    } uart_ctrl__DLL__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_ctrl__DLM__DATA__out_t;

    typedef struct {
        uart_ctrl__DLM__DATA__out_t DATA;
    } uart_ctrl__DLM__out_t;

    typedef struct {
        logic [1:0] value;
    } uart_ctrl__LCR__WLS__out_t;

    typedef struct {
        logic value;
    } uart_ctrl__LCR__PEN__out_t;

    typedef struct {
        logic value;
    } uart_ctrl__LCR__DLAB__out_t;

    typedef struct {
        uart_ctrl__LCR__WLS__out_t WLS;
        uart_ctrl__LCR__PEN__out_t PEN;
        uart_ctrl__LCR__DLAB__out_t DLAB;
    } uart_ctrl__LCR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_ctrl__IER__DATA__out_t;

    typedef struct {
        uart_ctrl__IER__DATA__out_t DATA;
    } uart_ctrl__IER__out_t;

    typedef struct {
        logic value;
    } uart_ctrl__FCR__FIFO_EN__out_t;

    typedef struct {
        uart_ctrl__FCR__FIFO_EN__out_t FIFO_EN;
    } uart_ctrl__FCR__out_t;

    typedef struct {
        logic [7:0] value;
    } uart_ctrl__MCR__DATA__out_t;

    typedef struct {
        uart_ctrl__MCR__DATA__out_t DATA;
    } uart_ctrl__MCR__out_t;

    typedef struct {
        uart_ctrl__RBR_THR__out_t RBR_THR;
        uart_ctrl__DLL__out_t DLL;
        uart_ctrl__DLM__out_t DLM;
        uart_ctrl__LCR__out_t LCR;
        uart_ctrl__IER__out_t IER;
        uart_ctrl__FCR__out_t FCR;
        uart_ctrl__MCR__out_t MCR;
    } uart_ctrl__out_t;
endpackage
