// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module uart_ctrl (
        input wire clk,
        input wire rst,

        apb3_intf.slave s_apb,

        input uart_ctrl_pkg::uart_ctrl__in_t hwif_in,
        output uart_ctrl_pkg::uart_ctrl__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert_bad_addr_width: assert($bits(s_apb.PADDR) >= uart_ctrl_pkg::UART_CTRL_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_apb.PADDR), uart_ctrl_pkg::UART_CTRL_MIN_ADDR_WIDTH);
            assert_bad_data_width: assert($bits(s_apb.PWDATA) == uart_ctrl_pkg::UART_CTRL_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_apb.PWDATA), uart_ctrl_pkg::UART_CTRL_DATA_WIDTH);
        end
    `endif

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb.PSEL) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb.PWRITE;
                    cpuif_addr <= {s_apb.PADDR[5:2], 2'b0};
                    cpuif_wr_data <= s_apb.PWDATA;
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end
    assign cpuif_wr_biten = '1;

    // Response
    assign s_apb.PREADY = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb.PRDATA = cpuif_rd_data;
    assign s_apb.PSLVERR = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic RBR_THR;
        logic DLL;
        logic DLM;
        logic LCR;
        logic IER;
        logic IIR;
        logic FCR;
        logic LSR;
        logic MCR;
        logic MSR;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.RBR_THR = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.DLL = cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.DLM = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.LCR = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.IER = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.IIR = cpuif_req_masked & (cpuif_addr == 6'h14) & !cpuif_req_is_wr;
        decoded_reg_strb.FCR = cpuif_req_masked & (cpuif_addr == 6'h18);
        decoded_reg_strb.LSR = cpuif_req_masked & (cpuif_addr == 6'h1c) & !cpuif_req_is_wr;
        decoded_reg_strb.MCR = cpuif_req_masked & (cpuif_addr == 6'h20);
        decoded_reg_strb.MSR = cpuif_req_masked & (cpuif_addr == 6'h24) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } DATA;
        } RBR_THR;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } DATA;
        } DLL;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } DATA;
        } DLM;
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } WLS;
            struct {
                logic next;
                logic load_next;
            } PEN;
            struct {
                logic next;
                logic load_next;
            } DLAB;
        } LCR;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } DATA;
        } IER;
        struct {
            struct {
                logic next;
                logic load_next;
            } FIFO_EN;
        } FCR;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } DATA;
        } MCR;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [7:0] value;
            } DATA;
        } RBR_THR;
        struct {
            struct {
                logic [7:0] value;
            } DATA;
        } DLL;
        struct {
            struct {
                logic [7:0] value;
            } DATA;
        } DLM;
        struct {
            struct {
                logic [1:0] value;
            } WLS;
            struct {
                logic value;
            } PEN;
            struct {
                logic value;
            } DLAB;
        } LCR;
        struct {
            struct {
                logic [7:0] value;
            } DATA;
        } IER;
        struct {
            struct {
                logic value;
            } FIFO_EN;
        } FCR;
        struct {
            struct {
                logic [7:0] value;
            } DATA;
        } MCR;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: uart_ctrl.RBR_THR.DATA
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.RBR_THR.DATA.value;
        load_next_c = '0;
        if(decoded_reg_strb.RBR_THR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.RBR_THR.DATA.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.RBR_THR.DATA.next;
            load_next_c = '1;
        end
        field_combo.RBR_THR.DATA.next = next_c;
        field_combo.RBR_THR.DATA.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.RBR_THR.DATA.value <= 8'h0;
        end else begin
            if(field_combo.RBR_THR.DATA.load_next) begin
                field_storage.RBR_THR.DATA.value <= field_combo.RBR_THR.DATA.next;
            end
        end
    end
    assign hwif_out.RBR_THR.DATA.value = field_storage.RBR_THR.DATA.value;
    assign hwif_out.RBR_THR.RSVD.value = 24'h0;
    // Field: uart_ctrl.DLL.DATA
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DLL.DATA.value;
        load_next_c = '0;
        if(decoded_reg_strb.DLL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DLL.DATA.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.DLL.DATA.next = next_c;
        field_combo.DLL.DATA.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.DLL.DATA.value <= 8'h0;
        end else begin
            if(field_combo.DLL.DATA.load_next) begin
                field_storage.DLL.DATA.value <= field_combo.DLL.DATA.next;
            end
        end
    end
    assign hwif_out.DLL.DATA.value = field_storage.DLL.DATA.value;
    // Field: uart_ctrl.DLM.DATA
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DLM.DATA.value;
        load_next_c = '0;
        if(decoded_reg_strb.DLM && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DLM.DATA.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.DLM.DATA.next = next_c;
        field_combo.DLM.DATA.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.DLM.DATA.value <= 8'h0;
        end else begin
            if(field_combo.DLM.DATA.load_next) begin
                field_storage.DLM.DATA.value <= field_combo.DLM.DATA.next;
            end
        end
    end
    assign hwif_out.DLM.DATA.value = field_storage.DLM.DATA.value;
    // Field: uart_ctrl.LCR.WLS
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.LCR.WLS.value;
        load_next_c = '0;
        if(decoded_reg_strb.LCR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.LCR.WLS.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.LCR.WLS.next = next_c;
        field_combo.LCR.WLS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.LCR.WLS.value <= 2'h3;
        end else begin
            if(field_combo.LCR.WLS.load_next) begin
                field_storage.LCR.WLS.value <= field_combo.LCR.WLS.next;
            end
        end
    end
    assign hwif_out.LCR.WLS.value = field_storage.LCR.WLS.value;
    // Field: uart_ctrl.LCR.PEN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.LCR.PEN.value;
        load_next_c = '0;
        if(decoded_reg_strb.LCR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.LCR.PEN.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.LCR.PEN.next = next_c;
        field_combo.LCR.PEN.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.LCR.PEN.value <= 1'h0;
        end else begin
            if(field_combo.LCR.PEN.load_next) begin
                field_storage.LCR.PEN.value <= field_combo.LCR.PEN.next;
            end
        end
    end
    assign hwif_out.LCR.PEN.value = field_storage.LCR.PEN.value;
    // Field: uart_ctrl.LCR.DLAB
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.LCR.DLAB.value;
        load_next_c = '0;
        if(decoded_reg_strb.LCR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.LCR.DLAB.value & ~decoded_wr_biten[7:7]) | (decoded_wr_data[7:7] & decoded_wr_biten[7:7]);
            load_next_c = '1;
        end
        field_combo.LCR.DLAB.next = next_c;
        field_combo.LCR.DLAB.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.LCR.DLAB.value <= 1'h0;
        end else begin
            if(field_combo.LCR.DLAB.load_next) begin
                field_storage.LCR.DLAB.value <= field_combo.LCR.DLAB.next;
            end
        end
    end
    assign hwif_out.LCR.DLAB.value = field_storage.LCR.DLAB.value;
    // Field: uart_ctrl.IER.DATA
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.IER.DATA.value;
        load_next_c = '0;
        if(decoded_reg_strb.IER && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.IER.DATA.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.IER.DATA.next = next_c;
        field_combo.IER.DATA.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.IER.DATA.value <= 8'h0;
        end else begin
            if(field_combo.IER.DATA.load_next) begin
                field_storage.IER.DATA.value <= field_combo.IER.DATA.next;
            end
        end
    end
    assign hwif_out.IER.DATA.value = field_storage.IER.DATA.value;
    // Field: uart_ctrl.FCR.FIFO_EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FCR.FIFO_EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.FCR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FCR.FIFO_EN.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.FCR.FIFO_EN.next = next_c;
        field_combo.FCR.FIFO_EN.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FCR.FIFO_EN.value <= 1'h0;
        end else begin
            if(field_combo.FCR.FIFO_EN.load_next) begin
                field_storage.FCR.FIFO_EN.value <= field_combo.FCR.FIFO_EN.next;
            end
        end
    end
    assign hwif_out.FCR.FIFO_EN.value = field_storage.FCR.FIFO_EN.value;
    // Field: uart_ctrl.MCR.DATA
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.MCR.DATA.value;
        load_next_c = '0;
        if(decoded_reg_strb.MCR && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.MCR.DATA.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.MCR.DATA.next = next_c;
        field_combo.MCR.DATA.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.MCR.DATA.value <= 8'h0;
        end else begin
            if(field_combo.MCR.DATA.load_next) begin
                field_storage.MCR.DATA.value <= field_combo.MCR.DATA.next;
            end
        end
    end
    assign hwif_out.MCR.DATA.value = field_storage.MCR.DATA.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[10];
    assign readback_array[0][7:0] = (decoded_reg_strb.RBR_THR && !decoded_req_is_wr) ? field_storage.RBR_THR.DATA.value : '0;
    assign readback_array[0][31:8] = (decoded_reg_strb.RBR_THR && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[1][7:0] = (decoded_reg_strb.DLL && !decoded_req_is_wr) ? field_storage.DLL.DATA.value : '0;
    assign readback_array[1][31:8] = '0;
    assign readback_array[2][7:0] = (decoded_reg_strb.DLM && !decoded_req_is_wr) ? field_storage.DLM.DATA.value : '0;
    assign readback_array[2][31:8] = '0;
    assign readback_array[3][1:0] = (decoded_reg_strb.LCR && !decoded_req_is_wr) ? field_storage.LCR.WLS.value : '0;
    assign readback_array[3][2:2] = '0;
    assign readback_array[3][3:3] = (decoded_reg_strb.LCR && !decoded_req_is_wr) ? field_storage.LCR.PEN.value : '0;
    assign readback_array[3][6:4] = '0;
    assign readback_array[3][7:7] = (decoded_reg_strb.LCR && !decoded_req_is_wr) ? field_storage.LCR.DLAB.value : '0;
    assign readback_array[3][31:8] = '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.IER && !decoded_req_is_wr) ? field_storage.IER.DATA.value : '0;
    assign readback_array[4][31:8] = '0;
    assign readback_array[5][0:0] = (decoded_reg_strb.IIR && !decoded_req_is_wr) ? hwif_in.IIR.TYPE.next : '0;
    assign readback_array[5][3:1] = (decoded_reg_strb.IIR && !decoded_req_is_wr) ? hwif_in.IIR.ID.next : '0;
    assign readback_array[5][31:4] = '0;
    assign readback_array[6][0:0] = (decoded_reg_strb.FCR && !decoded_req_is_wr) ? field_storage.FCR.FIFO_EN.value : '0;
    assign readback_array[6][31:1] = '0;
    assign readback_array[7][0:0] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.DR.next : '0;
    assign readback_array[7][1:1] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.OE.next : '0;
    assign readback_array[7][2:2] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.PE.next : '0;
    assign readback_array[7][3:3] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.FE.next : '0;
    assign readback_array[7][4:4] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.BI.next : '0;
    assign readback_array[7][5:5] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.THRE.next : '0;
    assign readback_array[7][6:6] = (decoded_reg_strb.LSR && !decoded_req_is_wr) ? hwif_in.LSR.TEMT.next : '0;
    assign readback_array[7][31:7] = '0;
    assign readback_array[8][7:0] = (decoded_reg_strb.MCR && !decoded_req_is_wr) ? field_storage.MCR.DATA.value : '0;
    assign readback_array[8][31:8] = '0;
    assign readback_array[9][7:0] = (decoded_reg_strb.MSR && !decoded_req_is_wr) ? hwif_in.MSR.DATA.next : '0;
    assign readback_array[9][31:8] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<10; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
